Mudi/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Mudi_DataAccess.Repository.IRepository;
using Mudi_DataAccess;
using Mudi_Models;
using Mudi_Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//using System.Web.Mvc;

namespace Mudi.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class CategoryController : Controller
    {

        private readonly ICategoryRepository _catRepo;
        public CategoryController(ICategoryRepository catRepo)
        {
            _catRepo = catRepo;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objList = _catRepo.GetAll();
            return View(objList);
        }



        //GET - CREATE
        public IActionResult Create()
        {
            
            return View();
        }

        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _catRepo.Add(obj);
                _catRepo.Save();
                TempData[WC.Success] = "Category created successfully";
                return RedirectToAction("Index");
            }
            TempData[WC.Error] = "Error while creating category";
            return View(obj);
        }

        //GET - EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _catRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _catRepo.Update(obj);
                _catRepo.Save();
                TempData[WC.Success] = "Category Edited successfully";
                return RedirectToAction("Index");
            }
            TempData[WC.Error] = "Error while editing category";
            return View(obj);

        }

        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _catRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _catRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            _catRepo.Remove(obj);
            _catRepo.Save();
            TempData[WC.Success] = "Category deleted successfully";
            return RedirectToAction("Index");


        }

        //check


    }
}

Mudi/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Mudi_DataAccess.Repository.IRepository;
using Mudi_Models;
using Mudi_Models.ViewModels;
using Mudi_Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Mudi.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderHeaderRepository _orderHRepo;
        private readonly IOrderDetailRepository _orderDRepo;
        private readonly IProductRepository _prodRepo;

        [BindProperty]
        public OrderVM OrderVM { get; set; }
        [BindProperty]
        public ProductVM ProductVM { get; set; }


        public OrderController(
        IOrderHeaderRepository orderHRepo, IOrderDetailRepository orderDRepo, IProductRepository prodRepo)
        {
            _orderDRepo = orderDRepo;
            _orderHRepo = orderHRepo;
            _prodRepo = prodRepo;
        }


        public IActionResult Index(string searchName = null, string searchEmail = null, string searchPhone = null, string Status = null)
        {
            OrderListVM orderListVM = new OrderListVM()
            {
                OrderHList = _orderHRepo.GetAll(),
                StatusList = WC.listStatus.ToList().Select(i => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = i,
                    Value = i
                })
            };
            if (!string.IsNullOrEmpty(searchName))
            {
                orderListVM.OrderHList = orderListVM.OrderHList.Where(u => u.FullName.ToLower().Contains(searchName.ToLower()));
            }
            if (!string.IsNullOrEmpty(searchEmail))
            {
                orderListVM.OrderHList = orderListVM.OrderHList.Where(u => u.Email.ToLower().Contains(searchEmail.ToLower()));
            }
            if (!string.IsNullOrEmpty(searchPhone))
            {
                orderListVM.OrderHList = orderListVM.OrderHList.Where(u => u.PhoneNumber.ToLower().Contains(searchPhone.ToLower()));
            }
            if (!string.IsNullOrEmpty(Status) && Status != "--Order Status--")
            {
                orderListVM.OrderHList = orderListVM.OrderHList.Where(u => u.OrderStatus.ToLower().Contains(Status.ToLower()));
            }

            return View(orderListVM);
        }
        public IActionResult Details(int id)
        {
            OrderVM = new OrderVM()
            {
                OrderHeader = _orderHRepo.FirstOrDefault(u => u.Id == id),
                OrderDetail = _orderDRepo.GetAll(o => o.OrderHeaderId == id, includeProperties: "Product")
            };

            return View(OrderVM);
        }
        public IActionResult DetailsUser(int id)
        {
            OrderVM = new OrderVM()
            {
                OrderHeader = _orderHRepo.FirstOrDefault(u => u.Id == id),
                OrderDetail = _orderDRepo.GetAll(o => o.OrderHeaderId == id, includeProperties: "Product")
            };

            return View(OrderVM);
        }
        public IActionResult IndexUser()
        {

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            OrderListVM orderListVM = new OrderListVM()
            {
                OrderHList = _orderHRepo.GetAll(u => u.ApplicationUserId == claim.Value)
            };
            return View(orderListVM);
        }

        [HttpPost]
        public IActionResult StartProcessing()
        {
            OrderHeader orderHeader = _orderHRepo.FirstOrDefault(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeader.OrderStatus = WC.StatusInProcess;
            _orderHRepo.Save();
            TempData[WC.Success] = "Action completed successfully";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult ShipOrder()
        {
            OrderHeader orderHeader = _orderHRepo.FirstOrDefault(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeader.OrderStatus = WC.StatusShipped;
            orderHeader.ShippingDate = DateTime.Now;
            _orderHRepo.Save();
            TempData[WC.Success] = "Action completed successfully";
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult CancelOrder()
        {
            OrderHeader orderHeader = _orderHRepo.FirstOrDefault(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeader.OrderStatus = WC.StatusCancelled;
            _orderHRepo.Save();
            TempData[WC.Success] = "Action completed successfully";
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult CompleteOrder(OrderVM orderVM)
        {
            OrderHeader orderHeader = _orderHRepo.FirstOrDefault(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeader.OrderStatus = WC.StatusCompleted;
            _orderHRepo.Save();

            TempData[WC.Success] = "Action completed successfully";
            var det = _orderDRepo.GetAll(u => u.OrderHeaderId == OrderVM.OrderHeader.Id);
            foreach (var detail in det)
            {
                Product prodTemp = _prodRepo.FirstOrDefault(x => x.Id == detail.ProductId);
                prodTemp.Stock -= detail.Qty;
            }
            _prodRepo.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

Mudi/Controllers/WishListController.cs
using Microsoft.AspNetCore.Mvc;
using Mudi_DataAccess.Repository.IRepository;
using System;
using Mudi_Models;
using Mudi_Models.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mudi_Utility;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace Mudi.Controllers
{
    public class WishListController : Controller
    {

        [BindProperty]
        public WishListVM WishListVM { get; set; }

        private readonly IWishListDetailRepository _wishDRepo;
        private readonly IProductRepository _prodRepo;



        public WishListController(IWishListDetailRepository wishDRepo
            , IProductRepository prodRepo)
        {
            _wishDRepo = wishDRepo;
            _prodRepo = prodRepo;
        }


        [Authorize]
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var objList = _wishDRepo.GetAll(u => u.ApplicationUserId == claim.Value).Join(_prodRepo.GetAll(),
                                                                                             w => w.ProductId,
                                                                                             p => p.Id,
                                                                                             (wish, product) => new
                                                                                             {
                                                                                                 wishListId= wish.Id,
                                                                                                 productName = product.Name,
                                                                                                 productPrice = product.Price,
                                                                                                 productStock=product.Stock,
                                                                                                 productId = product.Id
                                                                         
                                                                                             });
            List<WishListVM> WishListVM = new List<WishListVM>();

            foreach (var details in objList)
            {
                WishListVM wishList = new WishListVM()
                {
                    Id= details.wishListId,
                    ProductId = details.productId,
                    ProductName=details.productName,
                    UnitPrice=details.productPrice,
                    Stock=details.productStock
                };
                WishListVM.Add(wishList);
            }
            return View(WishListVM);  
        }

       [Authorize]
        public IActionResult Add(int id)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            
            WishListDetail obj = new WishListDetail();
            obj=_wishDRepo.FirstOrDefault(u => u.ApplicationUserId == claim.Value && u.ProductId == id);
            if(obj == null) //product is not in wishlist of the user
            {
                WishListDetail obj1 = new WishListDetail();
                obj1.ApplicationUserId = claim.Value;
                obj1.ProductId = id;
                _wishDRepo.Add(obj1);
                var incProdPopular = _prodRepo.FirstOrDefault(u => u.Id == id);
                incProdPopular.ProductPopularity++;
                _prodRepo.Update(incProdPopular);
                _wishDRepo.Save();
                TempData[WC.Success] = "Added to WishList successfully";

                List<WishList> wishLists = new List<WishList>();
                wishLists = HttpContext.Session.Get<List<WishList>>(WC.WishList);
                wishLists.Add(new WishList { ProductId = id });
                HttpContext.Session.Set(WC.WishList, wishLists);

        }
            else
            {
                TempData[WC.Info] = "Already In WishList";
            }
            
        return RedirectToAction("Index");
        }
        
        public IActionResult Delete(int? id)
        {
            var obj = _wishDRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            var incProdPopular = _prodRepo.FirstOrDefault(u => u.Id == id);
            incProdPopular.ProductPopularity--;
            _prodRepo.Update(incProdPopular);

            _wishDRepo.Remove(obj);
            _wishDRepo.Save();



            List<WishList> wishLists = new List<WishList>();
            wishLists = HttpContext.Session.Get<List<WishList>>(WC.WishList);

            var itemToRemove = wishLists.SingleOrDefault(r => r.ProductId == id);
            if (itemToRemove != null)
            {
                wishLists.Remove(itemToRemove);
            }

            HttpContext.Session.Set(WC.SessionCart, wishLists);

            TempData[WC.Success] = "Product Removed From WishList";
            return RedirectToAction("Index");


        }
    }
}

Mudi/Views/Home/AboutUs.cshtml
<section id="about">
    
    <div class="body px-5 mb-5">
        <div class="font-size-20 font-rubik text-center pb-2"><strong>Our Story</strong></div>
        <div>Mudi.com is an online shop in Dhaka, Bangladesh. We believe time is valuable to our fellow Dhaka residents, and that they should not have to waste hours in traffic, brave harsh weather and wait in line just to buy necessities like eggs!&nbsp; This is why we deliver every day needs to our customers’ door-steps across Dhaka.<br><br></div>
        <div>Mudi.com is a work in progress, and we hope to get better over time. We are firm believers in using technology and education to improve Bangladesh, and we will continue to invest all our effort in pushing the boundaries of technology.</div>
        <div>If you have ideas on how we can improve, we would love to hear from you. Please do email us at <strong>info@mudi.com</strong>.<br><br></div>
        <div>We deliver all kind of grocery items such as cooking items, beverage, bread & bakery, snacks, milk & dairy, beauty and body care, health care, home & cleaning items and daily needs to customer doors by ensuring quality, faster delivery and reasonable price. We are ready to manage customers’ hassle regarding daily, weekly and monthly grocery bazaar for Online Grocery Shopping with our own expertise to save their time, energy and money.<br><br></div>
    </div>
</section>

Mudi/Views/Home/ContactUs.cshtml
@model Mudi_Models.ViewModels.ContactUsVM

<h1>Contact Us</h1>
<section class="mb-4">

    <div class="row">
        <!--Form column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form method="post">

                <div class="row">
                    <!--Name-->

                    <div class="col-md-6">
                        <div class="md-form mb-0 pt-2">
                            <label>Name</label>
                            <input asp-for="ApplicationUser.FullName" type="text" class="form-control" />
                            <span asp-validation-for="ApplicationUser.FullName" class="text-danger"></span>
                        </div>
                    </div>

                    <!--Name-->
                    <!--phone no-->
                    <div class="col-md-6">
                        <div class="md-form mb-0 pt-2">
                            <label>Phone</label>
                            <input asp-for="ApplicationUser.PhoneNumber" type="text" class="form-control" />
                            <span asp-validation-for="ApplicationUser.PhoneNumber" class="text-danger"></span>
                        </div>
                    </div>
                    <!--phone no-->
                    <!--Email-->
                    <div class="col-md-6">
                        <div class="md-form mb-0 pt-2">
                            <label>Email</label>
                            <input asp-for="ApplicationUser.Email" type="text" class="form-control" />
                            <span asp-validation-for="ApplicationUser.Email" class="text-danger"></span>

                        </div>
                    </div>
                    <!--Email-->
                </div>

                <!--Subject-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 pt-2">
                            <label for="subject" class="">Subject:</label>
                            <input type="text" id="subject" name="subject" class="form-control">
                        </div>
                    </div>
                </div>
                <!--!Subject-->
                <!--Message-->
                <div class="row">
                    <div class="col-md-12">

                        <div class="md-form pt-2">
                            <label for="message">Message:</label>
                            <textarea type="text" id="message" name="message" rows="5" class="form-control md-textarea"></textarea>
                        </div>

                    </div>
                </div>
                <!--!Message-->
                <!--Submit Button-->
                <div class="text-center text-md-left pt-2">
                    <button type="submit" class="btn btn-success form-control ">
                        <span>Send</span>
                    </button>
                </div>
                <!--Submit Button-->
            </form>
        </div>
        <!--!Form column-->

    </div>

</section>

Mudi/Views/Home/Details.cshtml
@model Mudi_Models.ViewModels.DetailsVM
@using Mudi_Utility

<div class="">
    <form method="post">
        <input asp-for="@Model.Product.Id" hidden />
        <div class="container backgroundWhite pt-4">
            <div class="card" style="border:1px solid #000000; ">
                <div class="card-header bg-dark text-light ml-0 row container" style="border-radius: 0px;">
                    <div class="col-12 col-md-6">
                        <h1 class="text-white">@Model.Product.Name</h1>
                    </div>
                    <div class="col-12 col-md-6 text-md-right">
                        <h1 class="text-warning"><span> ৳ </span> @((Model.Product.Price))</h1>
                    </div>
                </div>
                <div class="card-body">
                    <div class="container rounded p-2">
                        <div class="row">
                            <div class="col-12 col-lg-4 p-1 text-center">
                                <img src="@Mudi_Utility.WC.ImagePath@Model.Product.Image" width="100%" class="rounded" />
                            </div>
                            <div class="col-12 col-lg-8">
                                <div class="row pl-3">

                                    <div class="col-12">
                                        <span class="badge p-3 border text-dark" style="background-color:lavenderblush">@Model.Product.Category.Name</span>
                                        <h3 class="text-success"></h3>

                                        <p class="text-secondary">@Html.Raw(Model.Product.Description) </p>
                                    </div>
                                    @if (!Model.ExistsInCart && Model.Product.Stock > 1)
                                    {
                                        <div class="col-12">
                                            Quantity:
                                        </div>
                                        <div class="col-12">

                                            <input asp-for="@Model.Product.TempQty" class="form-control" />
                                            
                                            <span asp-validation-for="@Model.Product.TempQty" class="text-danger"></span>
                                        </div>
                                    }

                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer bg-dark">
                    <div class="row">
                        <div class="col-12 col-md-4 ">
                            @if (Model.ExistsWish)
                            {

                                <a class="btn btn-danger disabled w-100 form-control btn-lg"
                                  >
                                    Added in Wishlist <i class="fas fa-heart"></i>
                                </a>

                            }
                            else
                            {

                                <a class="btn btn-danger w-100 form-control btn-lg"
                                   asp-controller="WishList" asp-action="Add" asp-route-id="@Model.Product.Id">
                                    Add to Wishlist <i class="far fa-heart"></i>
                                </a>

                            }
                        </div>

                        <div class="col-12 col-md-4 ">

                            <a class="btn w-100 btn-success form-control btn-lg"
                               asp-controller="Home" asp-action="Index">
                                Back to Products
                            </a>
                        </div>

                        <div class="col-12 col-md-4 ">
                            @if (Model.ExistsInCart)
                            {
                                <a asp-action="RemoveFromCart" asp-route-id="@Model.Product.Id" class="btn btn-warning btn-square form-control btn-lg" style="height:50px;">Remove from Cart</a>
                            }
                            else if (Model.Product.Stock > 1)
                            {

                                <button type="submit" asp-route-id="@Model.Product.Id" class="btn btn-info form-control btn-lg" style="height:50px;">Add to Cart</button>
                            }
                            else
                            {
                                <button  class="btn btn-info form-control disabled btn-lg" style="height:50px;">Out Of Stock</button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Mudi/Views/Home/Index.cshtml
@model Mudi_Models.ViewModels.HomeVM
@using Mudi_Utility

@if (User.IsInRole(Mudi_Utility.WC.AdminRole))
{
    <div class="card-group">
        <div class="card">
            @*<img class="card-img-top" src="..." alt="Card image cap">*@
            <div class="card-body">
                <h5 class="card-title text-center">Category</h5>

                <p class="card-text text-center">@Model.Categories.Count()</p>
                <a asp-controller="Category" asp-action="Index" class="btn w-100 btn-primary stretched-link">View Category</a>
            </div>
        </div>
        <div class="card">
            @*<img class="card-img-top" src="..." alt="Card image cap">*@
            <div class="card-body">
                <h5 class="card-title text-center">Product</h5>

                <p class="card-text text-center">@Model.Products.Count()</p>
                <a asp-controller="Product" asp-action="Index" class="btn w-100 btn-primary stretched-link">View Product</a>
            </div>
        </div>
        <div class="card">
            @*<img class="card-img-top" src="..." alt="Card image cap">*@
            <div class="card-body">
                <h5 class="card-title text-center">Order</h5>
                <p class="card-text text-center">@Model.OrderHList.Count(u => u.OrderStatus != WC.StatusCancelled && u.OrderStatus != WC.StatusCompleted)</p>
                <a asp-controller="Order" asp-action="Index" class="btn w-100 btn-primary stretched-link">View Order</a>

            </div>
        </div>
    </div>
}
else
{
    <div class="container">
        <div class="text-center">
            <button class="btn btn-dark filter-button" data-filter="all">All</button>
            @foreach (var obj in Model.Categories)
            {
                <button class="btn btn-outline-secondary filter-button" data-filter="@obj.Name.Replace(' ','_')">
                    @obj.Name
                </button>
            }
        </div>
        <br />
        <div class="row">
            @foreach (var prod in Model.Products)
            {
                <partial name="_IndividualProductCard" model="prod" />
                //display all product
            }
        </div>
    </div>
}

@section Scripts{
    <script>
        $(document).ready(function () {
            $(".filter-button").click(function () {
                var value = $(this).attr('data-filter');
                if (value == "all") {
                    $('.filter').show('1000');
                }
                else {
                    $(".filter").not('.' + value).hide('3000');
                    $('.filter').filter('.' + value).show('3000');
                }
            });
        });
    </script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
}