Mudi/Controllers/WebSiteDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Mudi_DataAccess.Repository.IRepository;
using Mudi_Models;
using Mudi_Models.ViewModels;
using Mudi_Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Mudi.Controllers
{
    public class WebSiteDetailController : Controller
    {
        private readonly IWebSiteDetailRepository _webDRepo;

        [BindProperty]
        public WebSiteDetailVM WebSiteDetailVM { get; set; }

        public WebSiteDetailController(IWebSiteDetailRepository webDRepo)
        {
            _webDRepo = webDRepo;

        }



        public IActionResult Index()
        {
            IEnumerable<WebSiteDetail> objList = _webDRepo.GetAll();
            return View(objList);
        }

        

        //GET - EDIT
        public IActionResult EditAboutUs(int id)
        {
            var obj = _webDRepo.FirstOrDefault(u => u.Id == id);

            WebSiteDetailVM = new WebSiteDetailVM();
            WebSiteDetailVM.WebSiteDetailId = id;
            WebSiteDetailVM.AboutUs = obj.AboutUs;
            WebSiteDetailVM.ContactUs = obj.ContactUs;
            return View(WebSiteDetailVM);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAboutUsPost(WebSiteDetailVM WebSiteDetailVM)
        {
            var obj = _webDRepo.FirstOrDefault(u => u.Id == WebSiteDetailVM.WebSiteDetailId);
            obj.AboutUs = WebSiteDetailVM.AboutUs;
            _webDRepo.Update(obj);
            _webDRepo.Save();
            TempData[WC.Success] = "About Us Edited successfully";
            return RedirectToAction("Index");

            TempData[WC.Error] = "Error while editing category";
            //return View(obj);

        }
        //GET - EDIT
        public IActionResult EditContactUs(int id)
        {
            
            var obj = _webDRepo.FirstOrDefault(u => u.Id == id);

            WebSiteDetailVM = new WebSiteDetailVM();
            WebSiteDetailVM.WebSiteDetailId = id;
            WebSiteDetailVM.ContactUs = obj.ContactUs;
            WebSiteDetailVM.AboutUs = obj.AboutUs;
            return View(WebSiteDetailVM);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditContactUsPost()
        {
                
                var obj = _webDRepo.FirstOrDefault(u => u.Id == WebSiteDetailVM.WebSiteDetailId);
                obj.ContactUs = WebSiteDetailVM.ContactUs;
                _webDRepo.Update(obj);
                _webDRepo.Save();
                TempData[WC.Success] = "Contact Us Edited successfully";
                return RedirectToAction("Index");
            
            TempData[WC.Error] = "Error while editing category";
            //return View(obj);

        }

    }
}

Mudi/Views/WebSiteDetail/EditAboutUs.cshtml
@model Mudi_Models.ViewModels.WebSiteDetailVM

<form method="post">
    <input asp-for="WebSiteDetailId" hidden />
    <div class="border p-3 bg-white">


        <div class="form-group row">
        </div>

        <h2>Edit About Us</h2>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-md-12">

                        <div class="md-form pt-2">

                            <textarea asp-for="AboutUs" type="text" id="message" name="message" rows="5" class="form-control md-textarea"></textarea>
                        </div>

                    </div>
                    <span asp-validation-for="AboutUs" class="text-danger"></span>

                </div>


                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <div class="container p-3 my-3">
                                <button type="submit" class="btn btn-success form-control ">
                                    <span>Update</span>
                                </button>
                            </div>
                        </div>

                        <div class="col">
                            <div class="container p-3 my-3">
                                <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }



}

Mudi/Views/WebSiteDetail/EditContactUs.cshtml
@model Mudi_Models.ViewModels.WebSiteDetailVM

<form method="post">
    <input asp-for="WebSiteDetailId" hidden />
    <div class="border p-3 bg-white">


        <div class="form-group row">
        </div>
        <div class="row">
            <div class="col-8">
                <h2>Edit Contact Us</h2>
                <div class="form-group row py-2">
                    <div class="col-md-12">

                        <div class="md-form pt-2">

                            <textarea asp-for=@Model.ContactUs type="text" id="message" name="message" rows="5" class="form-control md-textarea"></textarea>
                        </div>

                    </div>
                    <span asp-validation-for="ContactUs" class="text-danger"></span>

                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <div class="container p-3 my-3">
                                <a asp-action="EditContactUs" asp-controller="WebSiteDetail" class="btn btn-success w-100">Update</a>

                            </div>
                        </div>

                        <div class="col">
                            <div class="container p-3 my-3">
                                <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                            </div>

                        </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }



}

Mudi/Views/WebSiteDetail/Index.cshtml
@model IEnumerable<Mudi_Models.WebSiteDetail>


@if (Model.Count() ==1)
{
    <h2>About Us</h2>
    <section class="mb-4">

        <div class="row">
            @foreach (var obj in Model)
            {
                <!--Form column-->
                <div class="col-md-9 mb-md-0 mb-5">
                    <form method="post">

                        <!--Message-->
                        <div class="row">
                            <div class="col-md-12">

                                <div class="md-form pt-2">

                                    <textarea disabled type="text" id="message" name="message" rows="5" class="form-control md-textarea">@obj.AboutUs</textarea>
                                </div>

                            </div>
                        </div>
                        <!--!Message-->
                        <!--Edit Button-->
                        <div class="container p-3 my-3">
                            <a asp-controller="WebSiteDetail" asp-route-Id="@obj.Id" asp-action="EditAboutUs" class="btn btn-primary mx-2">
                                <i class="fas fa-edit"> Edit</i>
                            </a>
                        </div>
                        <hr />
                        <h2>Contact Us</h2>
                        <div class="row">
                            <div class="col-md-12">

                                <div class="md-form pt-2">
                                    <textarea disabled type="text" id="message" name="message" rows="5" class="form-control md-textarea">@obj.ContactUs</textarea>
                                </div>

                            </div>
                        </div>
                        <!--!Message-->
                        <!--Submit Button-->
                        <div class="container p-3 my-3">
                            <a asp-controller="WebSiteDetail" asp-route-Id="@obj.Id" asp-action="EditContactUs" class="btn btn-primary mx-2">
                                <i class="fas fa-edit"> Edit</i>
                            </a>
                        </div>

                        <!--Submit Button-->
                    </form>
                </div>
                <!--!Form column-->
            }
            </div>

    </section>
}